### ISSUE TITLE
How to _record_ (download) a Mediathek movie ?

### ISSUE THREAD

**Issue by Wikinaut** [raptor2101/Mediathek#66] opened 2016-01-23 14:03 UTC
On my PCs, I use MediathekView to download movies. 

#### My question: 

how can I use OSMC / Mediathek AddOn to download a movie ?

**Comment by raptor2101** [comment] 2016-01-26 19:41
duplicate of #63

**Closed by raptor2101** 2016-01-26 19:41 UTC

**Comment by Wikinaut** [comment] 2016-01-26 19:43
(correct!)
